alias please='sudo'
alias src='source ~/.zshrc'
alias c='clear'
alias pvpn='sudo protonvpn'
alias update='eos-update --yay'
alias scrn='sh ~/.screen-config.zsh'
alias ca='conda activate'
alias ce='conda info --envs'
